make:
	@echo "Hello Saeid hocam, have a nice day :)"
	@echo "Please write 'make compilehw4' command to create executable file named 'hw4' to run the program."
	@echo "After that you will have executable file hw4."
	@echo "as in example you should give input while running:  ./hw4 \" input \" "
	@echo "to run in valgrind you should use: valgrind ./hw4 \" input \" "
compilehw4:
	g++ *.cpp -o hw4
